### ISSUE TITLE
「Bug 反馈」AntiBot 几乎无法使用

### ISSUE THREAD

**Issue by Ikaleio** [Nova-Committee/CheatDetector#11]
在 Hypixel 服务器上 AntiBot 无法正确识别大厅 NPC 与反作弊假人，导致聊天内一直在报大厅 NPC 和反作弊假人的 FlyA 检测

**Comment by xia-mc** [comment]
AntiBot目前仅适用于PAS服务器。适用于Hypixel的AntiBot或许在下个版本(2.10.1)加入。

**Comment by xia-mc** [comment]
[Release 2.10.1](https://github.com/Nova-Committee/CheatDetector/releases/tag/2.10.1)已发布。
打开选项antiBotInTabList或许可以解决这个问题。

**Comment by d0j1a1701** [comment]
好的

**Comment by Ikaleio** [comment]
请问是否能更新一下 NextGen 分支？
