### ISSUE TITLE
「Bug 反馈」FlyC 误报

### ISSUE THREAD

**Issue by Ikaleio** [Nova-Committee/CheatDetector#12]
复现方式：

1. 进入 `mc.loyisa.cn` 测试服
2. 把 PvP 区的机器人连击打上天
3. 聊天栏出现一堆 FlyC，重复 motion 0.0

**Comment by Ikaleio** [comment]
推测问题在于 player.onGround 并不准，可采用计算与脚下方块碰撞箱重叠的方法强制获得准确的 onGround 数据。

**Comment by Ikaleio** [comment]
具体来说，直接计算实体 y 坐标下 0.5 格以内的方块是否与实体碰撞箱重叠大概就够了

**Comment by xia-mc** [comment]
感谢您反馈错误！


> 推测问题在于 player.onGround 并不准，可采用计算与脚下方块碰撞箱重叠的方法强制获得准确的 onGround 数据。

你的推测是正确的。```LoyisaIsImposter```有时会返回错误的onGround值。2.10.2的GroundSpoofB检查应该会纠正它。

**Comment by xia-mc** [comment]
[Release nextgen-2.10.2](https://github.com/Nova-Committee/CheatDetector/releases/tag/nextgen-2.10.2)已经发布。
