### ISSUE TITLE
「Bug 反馈」丢失 1.20.4 支持？

### ISSUE THREAD

**Issue by Ikaleio** [Nova-Committee/CheatDetector#9]
[Release 2.9.3](https://github.com/Nova-Committee/CheatDetector/releases/tag/2.9.3) 无法在 1.20.4 中加载，报错信息提到该 mod 仅兼容 1.20.2

**Comment by xia-mc** [comment]
是的，上一个1.20.4支持版本是[Release nextgen-2.5.0](https://github.com/Nova-Committee/CheatDetector/releases/tag/nextgen-2.5.0)

**Comment by xia-mc** [comment]
已经同步nextgen-2.9.4

**Comment by Ikaleio** [comment]
感谢。我昨天尝试自己迁移，但因为自己薄弱的 Fabricmod 开发经验没有完全修复成功，本来打算 PR Draft 的不过看起来你已经弄好了 Orz

**Comment by xia-mc** [comment]
很抱歉nextgen-2.9.4所有基于时间的检查似乎失效了orz
在你那边有出现吗？

**Comment by Ikaleio** [comment]
> 很抱歉nextgen-2.9.4所有基于时间的检查似乎失效了orz 在你那边有出现吗？

我并没有仔细测试，但在 Loyisa 测试服只看见了 FlyA, Velocity 0%0% 的检测。

昨天在 Hypixel 遇到了一个暴力黑客，AutoBlockA 检测似乎并不起作用

Velocity 检测似乎只能检测到 0%0%

Reach 检测十分的玄学

**Comment by Ikaleio** [comment]
另外 PAS 模式似乎会在重进服务器后自动关闭（AntiBot 是不是应该挪出 PAS 模式）

期待作者能一并合并 2.10.1 的更改

**Comment by Ikaleio** [comment]
另外，ClientSpoof 似乎在与 ViaFabricPlus 同时使用时不起作用。

**Comment by xia-mc** [comment]
> > 很抱歉nextgen-2.9.4所有基于时间的检查似乎失效了orz 在你那边有出现吗？
> 
> 我并没有仔细测试，但在 Loyisa 测试服只看见了 FlyA, Velocity 0%0% 的检测。
> 
> 昨天在 Hypixel 遇到了一个暴力黑客，AutoBlockA 检测似乎并不起作用
> 
> Velocity 检测似乎只能检测到 0%0%
> 
> Reach 检测十分的玄学

**AutoBlockA**检查包含尚未解决的问题，所以现在是不生效的；
**VelocityA**检查只能检测某一轴的击退被取消，客户端无法得知击退的方向、大小；
**ReachA**检查不包含延迟补偿，所以在高延迟下几乎不可用。


> 另外 PAS 模式似乎会在重进服务器后自动关闭（AntiBot 是不是应该挪出 PAS 模式）
> 
> 期待作者能一并合并 2.10.1 的更改

2.10.1将AntiBot挪出了PAS模式。默认情况下AntiBot可能不会生效，需要在```高级 模块```选项卡里启用某个模式。
```
antiBotMessage 适用于PAS服务器
antiBotLatency 从未更新过延迟的玩家
antiBotInTabList 不在在线列表中的玩家
```
[Release nextgen-2.10.1](https://github.com/Nova-Committee/CheatDetector/releases/tag/nextgen-2.10.1)


> 另外，ClientSpoof 似乎在与 ViaFabricPlus 同时使用时不起作用。

因为没搞清楚1.20.4客户端类型的发包，所以ClientSpoof模块被暂时移出。（2.10.1中删除了失效的选项）
